# Generated by Django 4.0.1 on 2022-02-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
