# Generated by Django 4.0.1 on 2022-03-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0005_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='slug',
            field=models.ForeignKey(default=1, max_length=150, on_delete=django.db.models.deletion.CASCADE, to='review_app.product'),
            preserve_default=False,
        ),
    ]
