# Generated by Django 4.0.1 on 2022-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0006_productreview_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='slug',
        ),
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
