# Generated by Django 4.0.1 on 2022-03-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0007_remove_productreview_slug_productreview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
